/*
 * Ayudas flotantes en lenguaje sencillo. Clave → { t: qué considerar, e: [ejemplos generales] }.
 * Para editar un texto basta con cambiarlo aquí; no afecta el cálculo.
 */
(function (root) {
  const A = {
    // ---------- Configuración y datos del caso ----------
    perfil: { t: 'Elija «Núcleo común» si su entidad no está supervisada por la SBS. Elija el perfil financiero si es un banco, caja, financiera o fondo supervisado: agrega preguntas propias de ese sector.', e: ['Un ministerio o una municipalidad: núcleo común.', 'Un banco estatal o una caja municipal: sistema financiero.'] },
    escala: { t: 'Indica cuántas personas suele atender su entidad. Solo cambia los umbrales de la pregunta sobre número de personas cuyos datos se usan.', e: ['Una municipalidad distrital o un hospital regional: alcance sectorial o local.', 'Un programa social nacional o una entidad de registro de identidad: alcance nacional masivo.'] },
    'caso:nombre': { t: 'Un nombre corto que cualquier colega entienda. Describa qué hace el sistema, no la marca de la herramienta.', e: ['«Asistente para responder consultas sobre trámites».', '«Modelo para priorizar inspecciones».'] },
    'caso:entidad': { t: 'Nombre de su institución. Solo aparece en el reporte que usted exporte.', e: ['Municipalidad Provincial de …', 'Hospital Regional de …'] },
    'caso:area': { t: 'El área que usará el sistema y responderá por sus resultados, aunque la parte técnica la haga otra área.', e: ['Oficina de Atención al Ciudadano.', 'Subgerencia de Fiscalización.'] },
    'caso:responsable': { t: 'La persona que responde por el uso del sistema en el día a día. Puede ser un cargo en lugar de un nombre.', e: ['Jefe de la Oficina de Atención al Ciudadano.', 'Coordinadora de Fiscalización.'] },
    'caso:fecha': { t: 'Fecha en que hace esta evaluación. Si el sistema cambia, conviene repetir la evaluación con nueva fecha.', e: ['2026-10-15'] },
    'caso:descripcion': { t: 'Explique en dos o tres frases qué hace el sistema, con qué información trabaja y quién usa sus resultados. Evite términos técnicos.', e: ['«Lee las solicitudes que llegan por la web, las clasifica por tema y sugiere una respuesta que un servidor revisa antes de enviar».', '«Estima qué establecimientos tienen más probabilidad de incumplir normas para planificar las visitas».'] },
    'caso:herramienta': { t: 'La herramienta, plataforma o proveedor que se usará. Si aún no está definida, escriba «por definir».', e: ['Asistente de IA contratado por la entidad.', 'Modelo desarrollado por el área de sistemas.'] },

    grupos: { t: 'Marque los grupos sobre los que el sistema tiene un efecto particular. El artículo 12 pide atender sus necesidades diferenciadas; la marca se registra en el reporte para que la evaluación de impacto lo considere.', e: ['Un asistente de trámites usado sobre todo por personas adultas mayores.', 'Un sistema de becas que evalúa a estudiantes menores de edad.'] },

    // ---------- Paso 0 ----------
    'ambito:publica': { t: 'Ministerios, organismos públicos, gobiernos regionales y locales, universidades públicas y demás entidades de la Ley del Procedimiento Administrativo General.', e: ['Un ministerio.', 'Una municipalidad provincial.'] },
    'ambito:empresa': { t: 'Empresas del Estado bajo FONAFE o de gobiernos regionales o locales.', e: ['Un banco estatal de desarrollo.', 'Una empresa municipal de agua.'] },
    'ambito:privado': { t: 'Empresas privadas, organizaciones de la sociedad civil, la academia privada y ciudadanos. Aplican además los artículos 31 y 32 del Reglamento.', e: ['Una fintech.', 'Una universidad privada.'] },
    'ambito:ninguna': { t: 'Elija esta opción en la gran mayoría de casos.', e: ['Un asistente que usan los servidores para su trabajo.'] },
    'ambito:personal': { t: 'Solo el uso de IA para fines estrictamente personales. Si una persona usa IA para tareas de su trabajo en la entidad, no es uso personal.', e: ['Personal: planificar un viaje familiar.', 'No es personal: redactar un informe de la oficina con un asistente de IA.'] },
    'ambito:defensa': { t: 'Solo sistemas para la defensa y seguridad nacional. La excepción exige respetar los principios del artículo 7; ante la duda, continúe con la evaluación.', e: ['Un sistema de vigilancia de fronteras de las Fuerzas Armadas.'] },
    'P0.1': { t: 'Responda «Sí» si el sistema aprende de datos o produce respuestas que no fueron programadas una por una. Responda «No» si solo aplica reglas fijas del tipo «si pasa A, haga B».', e: ['Sí: un asistente que redacta respuestas; un modelo que estima probabilidades.', 'No: una planilla con fórmulas; un formulario que valida que el DNI tenga 8 dígitos.'] },
    'P0.2': { t: 'Responda «Sí» si el sistema usa un modelo de IA propio o de un proveedor, aunque venga incluido dentro de otro software.', e: ['Sí: un correo o un procesador de textos con asistente de IA incorporado.', 'Sí: un servicio en la nube que transcribe audios automáticamente.'] },
    'P0.3': { t: 'Piense si el mismo resultado se lograría con reglas fijas o una automatización tradicional, más simple y más fácil de controlar. No cambia la clasificación, pero conviene evaluarlo antes de usar IA.', e: ['Sí bastaría: enviar un recordatorio siempre que falten 5 días para un vencimiento.', 'No bastaría: resumir cientos de documentos distintos o responder preguntas abiertas.'] },

    // ---------- Paso 1: usos prohibidos ----------
    A1: { t: 'Marque «Aplica» solo si el sistema está pensado para engañar o presionar a las personas para que decidan algo que no decidirían informadas. Informar o recomendar con transparencia no es manipular.', e: ['Aplica: mensajes que explotan el miedo o la urgencia para que alguien acepte un producto.', 'No aplica: un asistente que explica requisitos de un trámite.'] },
    A2: { t: 'Se refiere a sistemas capaces de causar daño físico o letal decidiendo sin intervención humana. Casi ningún proyecto administrativo tiene relación con esto.', e: ['Aplica: un dispositivo armado que decide por sí solo cuándo actuar.', 'No aplica: un sistema que agenda citas.'] },
    A3: { t: 'Vigilar o seguir de forma generalizada a muchas personas sin una ley que lo autorice, o de manera desproporcionada.', e: ['Aplica: rastrear la ubicación de todos los visitantes de un espacio público sin base legal.', 'No aplica: contar cuántas personas ingresan a una sede sin identificarlas.'] },
    A4: { t: 'Usar rasgos físicos (rostro, voz, huellas) para deducir origen étnico, religión, opinión política u orientación sexual; o evaluar a personas de forma que el resultado discrimine.', e: ['Aplica: clasificar a solicitantes según su apariencia en una foto.', 'No aplica: verificar que el rostro coincide con la foto del documento para iniciar sesión.'] },
    A5: { t: 'Reconocer a personas en tiempo real en calles, plazas u otros espacios públicos. Las excepciones son la verificación de identidad para un servicio digital y ciertas investigaciones de delitos graves previstas en la norma.', e: ['Aplica: cámaras que identifican a transeúntes al pasar.', 'No aplica: validar la identidad de quien ingresa a una plataforma con su consentimiento.'] },
    A6: { t: 'Predecir que alguien cometerá un delito según su perfil o personalidad. Apoyar a un investigador con hechos concretos y verificables de un caso existente no está prohibido.', e: ['Aplica: puntuar a ciudadanos según su «probabilidad de delinquir».', 'No aplica: ordenar evidencia de un expediente abierto para que un fiscal la revise.'] },
    AX1: { t: 'Dar un puntaje general a las personas por su comportamiento social para tratarlas peor en ámbitos que no tienen relación con ese comportamiento.', e: ['Aplica: negar un servicio por publicaciones en redes sociales.', 'No aplica: verificar el cumplimiento de requisitos de un beneficio.'] },
    AX2: { t: 'Usar la IA para evitar controles legales, ocultar información a supervisores o burlar controles antifraude o de lavado de activos.', e: ['Aplica: dividir operaciones para que no superen umbrales de reporte.', 'No aplica: detectar operaciones inusuales para reportarlas.'] },
    AX3: { t: 'Generar voz, imagen, video o textos que se hagan pasar por una persona o institución real para engañar.', e: ['Aplica: un audio falso de una autoridad pidiendo una transferencia.', 'No aplica: un avatar claramente identificado como asistente virtual.'] },

    // ---------- Paso 2: usos sensibles ----------
    N1: { t: 'Marque «Aplica» si el sistema ayuda a operar o controlar infraestructura que sostiene servicios esenciales para la población.', e: ['Aplica: ajustar automáticamente la presión de una red de agua potable.', 'No aplica: responder preguntas frecuentes sobre el servicio.'] },
    N2: { t: 'Si el sistema interviene en el acceso, la evaluación o el control de exámenes de niñas, niños o adolescentes. No aplica si solo complementa y el docente sigue evaluando.', e: ['Aplica: asignar vacantes escolares o calificar exámenes de forma automática.', 'No aplica: generar ejercicios de práctica que el docente revisa.'] },
    N3: { t: 'Si el sistema interviene en seleccionar, evaluar, contratar o despedir personas, o en fijar sus condiciones de trabajo.', e: ['Aplica: filtrar hojas de vida de postulantes.', 'No aplica: redactar el aviso de convocatoria.'] },
    N4: { t: 'Si el sistema decide o influye en quién recibe, sigue recibiendo o pierde un programa social, o en qué hogares se priorizan.', e: ['Aplica: priorizar hogares para un subsidio.', 'No aplica: informar a los beneficiarios la fecha de pago.'] },
    N5: { t: 'Si el sistema evalúa si una persona puede recibir un crédito o en qué condiciones. La detección de fraude no cuenta aquí.', e: ['Aplica: puntuar la capacidad de pago de solicitantes de un préstamo.', 'No aplica: alertar operaciones con tarjeta que parecen fraudulentas.'] },
    N6: { t: 'Si el sistema influye en quién accede a una atención de salud o a servicios que afectan la vida y el bienestar.', e: ['Aplica: decidir el orden de las citas según una estimación de gravedad.', 'No aplica: recordar a un paciente la hora de su cita.'] },
    N7: { t: 'Si el sistema ayuda a diagnosticar, tratar o priorizar pacientes, o analiza historias clínicas.', e: ['Aplica: sugerir diagnósticos a partir de radiografías.', 'No aplica: resumir el reglamento interno de un hospital.'] },
    N8: { t: 'Si el sistema intenta detectar emociones de trabajadores o estudiantes (por su rostro, voz o escritura). Se exceptúan fines médicos o de seguridad.', e: ['Aplica: medir el «ánimo» de los empleados durante reuniones.', 'No aplica: un botón para que el usuario califique la atención.'] },
    N9: { t: 'Supuesto abierto: cualquier otro uso que pueda afectar derechos y que además pueda estigmatizar o discriminar, o que sea muy difícil de supervisar por una persona.', e: ['Aplica: asignar automáticamente «perfiles de riesgo» a vecinos para priorizar inspecciones.', 'No aplica: traducir documentos internos.'] },
    NX1: { t: 'Construir perfiles de muchas personas combinando sus datos, o identificarlas con rostro, huella o voz.', e: ['Aplica: segmentar a toda la población usuaria según su comportamiento.', 'No aplica: estadísticas agregadas sin identificar a nadie.'] },
    NX2: { t: 'Si el sistema interviene en fiscalizar, sancionar, investigar o evaluar el riesgo de personas en seguridad, justicia, tributos o migraciones.', e: ['Aplica: seleccionar contribuyentes para fiscalización.', 'No aplica: responder preguntas generales sobre cómo pagar un tributo.'] },
    SF1: { t: 'Si el sistema evalúa o califica a empresas u otras contrapartes (no personas naturales) para darles créditos, líneas o garantías, o fija sus límites.', e: ['Aplica: calificar a empresas que solicitan financiamiento.', 'No aplica: resumir estados financieros para que un analista los lea.'] },
    SF2: { t: 'Si el sistema decide o prioriza el destino de fondos públicos o de fondos que la entidad administra por encargo.', e: ['Aplica: ordenar solicitudes para asignar un fondo concursable.', 'No aplica: conciliar los movimientos del fondo.'] },
    SF3: { t: 'Si el sistema interviene en evaluar o estructurar el financiamiento de proyectos, créditos compartidos entre varias entidades o decide en qué territorios colocar recursos.', e: ['Aplica: priorizar proyectos de infraestructura a financiar.', 'No aplica: buscar noticias públicas sobre un sector.'] },
    SF4: { t: 'Si terceros (canales, corresponsales, intermediarios) aplican a los clientes reglas o puntajes que definió la entidad.', e: ['Aplica: un puntaje de elegibilidad que usan los agentes corresponsales.', 'No aplica: material informativo para esos canales.'] },
    SF5: { t: 'Si el sistema es un modelo usado para gestionar riesgos (crédito, mercado, liquidez, operacional, lavado de activos) sujeto a la norma de riesgo de modelo de la SBS.', e: ['Aplica: un modelo de probabilidad de incumplimiento.', 'No aplica: un asistente que redacta informes de gestión.'] },
    SF6: { t: 'Si el sistema bloquea, cierra o restringe cuentas, tarjetas u operaciones de clientes, o decide si se revierten.', e: ['Aplica: congelar automáticamente una cuenta por sospecha.', 'No aplica: enviar una alerta para que un analista decida.'] },
    s3: { t: 'Márquelo solo si el caso de uso se rediseñó de verdad para que su resultado ya no influya en esa decisión, el Comité lo aprobó y hay documentos que lo acrediten. Agregar controles o supervisión no es un rediseño: baja el riesgo residual, pero el uso sigue siendo de riesgo alto. Dividir el sistema en partes para evitar la pregunta no cuenta.', e: ['Válido: el modelo pasó a dar estadísticas agregadas sin resultados por persona.', 'No válido: seguir usando el puntaje, pero llamarlo «referencial».'] },

    // ---------- Paso 3 ----------
    'info:publica': { t: 'Información que ya está publicada o que cualquiera puede obtener. Si ya está en un portal o en una norma, es pública.', e: ['Leyes, reglamentos y tarifas publicadas.', 'Comunicados de prensa ya difundidos.'] },
    'info:interna': { t: 'Información de trabajo que no está publicada pero no tiene datos protegidos. Su difusión no causaría daño relevante.', e: ['Borradores de procedimientos.', 'Actas de reuniones de coordinación sin datos personales.'] },
    'info:confidencial': { t: 'Información que la ley exceptúa de la publicidad o que pertenece a terceros: secretos comerciales, datos personales comunes, documentos de proveedores o usuarios.', e: ['Expedientes con nombres y direcciones de usuarios.', 'Propuestas técnicas de proveedores en evaluación.'] },
    'info:restringida': { t: 'Lo más delicado: información secreta o reservada, datos de salud u otros datos sensibles, secreto bancario o tributario, y contraseñas. Ante la duda entre dos niveles, elija el más alto.', e: ['Historias clínicas o datos biométricos.', 'Declaraciones tributarias o movimientos bancarios de personas.'] },
    'info:etiqueta': { t: 'Opcional. Si su entidad usa otro nombre para esta categoría, escríbalo para que quien lea el reporte haga la equivalencia.', e: ['«Uso restringido».', '«Confidencial nivel 2».'] },
    'herr:interno': { t: 'Un sistema instalado en la entidad o un espacio dedicado en la nube, contratado con garantías de que los datos no salen de ese entorno.', e: ['Un modelo instalado en los servidores de la entidad.', 'Una instancia privada contratada solo para la entidad.'] },
    'herr:catalogo': { t: 'Una herramienta que la entidad ya contrató y aprobó para uso del personal, con cuentas institucionales.', e: ['El asistente de IA incluido en la suite de oficina contratada.', 'Una plataforma aprobada por el área de seguridad.'] },
    'herr:nueva': { t: 'Una herramienta que se quiere usar pero que el área de seguridad todavía no ha evaluado. Mientras tanto, solo se admite con información pública.', e: ['Un servicio que un área encontró en internet y quiere probar.', 'La versión de prueba de un producto nuevo.'] },
    'herr:publica': { t: 'Herramientas gratuitas o de uso personal, sin contrato con la entidad. Pueden guardar y reutilizar lo que se les escribe.', e: ['Un chat de IA con cuenta de correo personal.', 'Una web gratuita para resumir o traducir documentos.'] },
    authC: { t: 'Responda «Sí» solo si el catálogo de herramientas aprobadas indica expresamente que esta herramienta puede recibir información confidencial.', e: ['Sí: el catálogo dice «apta hasta información confidencial».', 'No: el catálogo no dice nada o la limita a información interna.'] },
    authR: { t: 'Responda «Sí» solo si existe una autorización por escrito del Oficial de IA y de los responsables de datos personales y de seguridad para usar esta herramienta con información restringida.', e: ['Sí: hay un memorando de autorización para este caso.', 'No: se asume que «seguramente se puede».'] },
    'info-res': { t: 'Si puede quitar la información más delicada y trabajar solo con lo necesario, indique aquí el nuevo nivel. Debe existir un control que lo asegure.', e: ['Usar solo estadísticas agregadas en lugar de datos por persona.', 'Retirar nombres y documentos de identidad antes de procesar.'] },
    'herr-res': { t: 'Si cambiará a una herramienta o entorno más protegido, indíquelo aquí.', e: ['Pasar de un chat gratuito al asistente contratado por la entidad.', 'Pasar de la nube pública a un entorno dedicado.'] },
    'ev-info': { t: 'Describa en una frase qué medida se aplicó y cómo se comprueba.', e: ['«Se procesa solo el resumen sin datos personales; el sistema bloquea la carga de documentos completos».'] },

    // ---------- Rutas y medidas ----------
    ruta: { t: 'Elija la medida concreta que reduce este factor. Solo aparecen las que aplican. La medida debe estar implementada o ser condición antes de usar el sistema.', e: ['Reducir permisos para que el sistema solo proponga y una persona apruebe.', 'Anonimizar los datos antes de usarlos.'] },
    reduccion: { t: 'Elija cómo queda este factor con la medida aplicada. Solo puede bajar, nunca subir, y algunas medidas bajan como máximo un nivel.', e: ['De «ejecuta sin aprobación» a «ejecuta con aprobación previa».'] },
    evidencia: { t: 'Explique qué se hizo y dónde se puede verificar. Sin sustento, la reducción no debería aceptarse.', e: ['«Las respuestas quedan como borrador; el envío requiere aprobación del servidor responsable».', '«Informe de pruebas de sesgo del 10/10/2026».'] },

    // ---------- Paso 6 ----------
    S1: { t: 'Pida la clasificación «experimental» solo para pruebas de concepto sin datos reales ni efectos sobre personas, por un plazo acotado (la metodología usa 90 días como criterio interno; el Reglamento no fija un plazo).', e: ['Probar un asistente con documentos públicos antes de decidir si se contrata.', 'Entrenar un prototipo con datos sintéticos.'] },
    'S1.c': { t: 'Las cinco condiciones deben cumplirse a la vez. Si alguna no se cumple, el caso se evalúa con el procedimiento normal.', e: ['Datos ficticios, entorno aislado, 60 días, responsable designado e informe final: cumple.'] },
    S2: { t: 'Si usa una herramienta ya aprobada exactamente para el tipo de información, nivel de agencia y propósito que ya se evaluaron, puede heredar esa clasificación.', e: ['Usar el asistente aprobado para resumir documentos internos, como ya se autorizó.'] },
    S4: { t: 'Solicítela solo si necesita operar temporalmente mientras falta implementar un control. Es por un máximo de 6 meses y no baja el nivel.', e: ['Operar mientras se contrata la auditoría de seguridad, con revisión manual del 100 % de los resultados.'] },
    S5: { t: 'Para casos de nivel moderado que llevan un año funcionando bien, sin incidentes ni observaciones.', e: ['Un asistente de redacción interna con 12 meses de uso estable.'] },

    // ---------- Paso 7: ficha del agente ----------
    'acap:mision': { t: 'Qué debe lograr el agente, en una o dos frases, y para quién.', e: ['«Atender consultas sobre trámites y registrar cada caso en el sistema de atención».'] },
    'acap:limites': { t: 'Lo que el agente no debe hacer nunca, aunque técnicamente pudiera.', e: ['«No aprueba ni rechaza solicitudes».', '«No envía información fuera de la entidad».'] },
    'acap:conexiones': { t: 'Los sistemas, bases de datos o servicios a los que se conecta, y qué puede hacer en cada uno (leer, escribir, enviar).', e: ['«Correo institucional: leer y crear borradores».', '«Sistema de trámite: consultar el estado de expedientes».'] },
    'acap:frontera': { t: 'Hasta dónde llega el agente. Cuanto más sale de la entidad, mayores controles de identidad y datos se necesitan.', e: ['Solo dentro de la entidad: un agente que ordena documentos internos.', 'Varias organizaciones: un agente que coordina con proveedores o con otras entidades.'] },
    'acap:permitidas': { t: 'Acciones que el agente puede realizar sin pedir permiso cada vez. Deben ser reversibles y de bajo impacto.', e: ['Clasificar correos.', 'Crear borradores de respuesta.'] },
    'acap:aprobacion': { t: 'Acciones que solo puede ejecutar si una persona las aprueba antes. Incluya todas las irreversibles o que comprometen a la entidad.', e: ['Enviar comunicaciones oficiales.', 'Registrar pagos o modificar datos de un ciudadano.'] },
    'acap:prohibidas': { t: 'Acciones que el agente no puede realizar bajo ninguna circunstancia.', e: ['Eliminar registros.', 'Aceptar contratos o condiciones en nombre de la entidad.'] },
    'acap:apagado': { t: 'Márquelo si se probó que el agente puede detenerse de inmediato y que sus accesos pueden revocarse sin afectar otros sistemas.', e: ['Una prueba registrada en la que se desactivó el agente y se revocaron sus credenciales en minutos.'] },
    'acap:topes': { t: 'Límites de gasto, volumen u operaciones que el agente no puede superar.', e: ['«Máximo 200 respuestas por día».', '«Sin transacciones por encima de S/ 0: solo propone»'] },
    'acap:subagentes': { t: 'Si el agente usa otros agentes, ninguno puede tener más permisos que el agente que lo llama.', e: ['El agente principal solo lee: sus ayudantes tampoco pueden escribir.'] },
    'acap:registro': { t: 'Márquelo si queda registro de cada acción del agente, con fecha, qué hizo y quién la aprobó.', e: ['Bitácora consultable por el área de seguridad.'] },
    'acap:pruebas': { t: 'Qué pruebas se hicieron antes de usarlo y con qué resultados, incluidas pruebas de ataque o de mal uso.', e: ['«Se probaron 300 consultas reales anonimizadas: 96 % de respuestas correctas».', '«Se intentó engañarlo con instrucciones ocultas en documentos: no ejecutó acciones».'] },
    'acap:senales': { t: 'Marque las señales de alerta que se vigilarán durante la operación.', e: ['Acciones que se acercan a los límites.', 'Intentos de acceder a datos que no necesita.'] },
    'acap:supervisor': { t: 'Quién vigila al agente y puede detenerlo. Debe estar capacitado, tener tiempo y autoridad para intervenir.', e: ['Jefa de la Oficina de Atención al Ciudadano.'] },
    'acap:calibracion': { t: 'Márquelo si los supervisores rotan y se revisa periódicamente su criterio con casos cuya respuesta correcta ya se conoce, para evitar que aprueben todo por costumbre.', e: ['Cada mes se incluyen 10 casos de prueba entre los reales y se revisa si el supervisor los detecta.'] },
    'acap:reautorizacion': { t: 'Fecha en que se volverá a revisar la autorización. Además, cualquier cambio de alcance o permisos exige revisarla antes.', e: ['Riesgo alto: cada 3 meses.', 'Riesgo moderado: cada 6 meses.'] }
  };

  // Ayudas por nivel de cada factor (clave «factor:nivel»)
  const F = {
    'F1.1': ['Solo ayuda a quien lo usa en su propio trabajo; nadie más se ve afectado.', 'Sus resultados alimentan tareas internas, pero no deciden nada sobre personas o empresas.', 'Una persona decide sobre otros, pero el resultado del sistema pesa en esa decisión.', 'El sistema decide, o su resultado casi siempre se acepta tal cual.'],
    'F1.1e': [['Resumir un informe para leerlo más rápido.'], ['Clasificar documentos para archivarlos.'], ['Sugerir el orden de atención de solicitudes que un servidor revisa.'], ['Aprobar o rechazar solicitudes automáticamente.']],
    'F1.2': ['Solo quien usa el sistema.', 'Un área o proceso de la entidad.', 'Varias áreas, o personas y organizaciones externas identificadas.', 'La ciudadanía en general, muchos beneficiarios o recursos públicos importantes.'],
    'F1.2e': [['Un asistente personal de redacción.'], ['Un clasificador de correos de un área.'], ['Un sistema que responde a proveedores.'], ['Un asistente en el portal de trámites para todos los ciudadanos.']],
    'F1.3': ['No evalúa ni compara personas ni organizaciones.', 'Evalúa organizaciones con datos objetivos, sin rasgos personales.', 'Usa datos que podrían reflejar diferencias injustas, como zona, edad o tamaño.', 'Usa datos sensibles o datos históricos con sesgos conocidos.'],
    'F1.3e': [['Traducir documentos.'], ['Ordenar proveedores por puntualidad de entregas.'], ['Priorizar distritos para una campaña según datos de años anteriores.'], ['Evaluar postulantes con datos de contrataciones pasadas que favorecían a un grupo.']],
    'F1.4': ['Cualquier error se detecta y corrige al instante.', 'Corregir un error toma algo de trabajo, pero es posible.', 'Es difícil explicar por qué el sistema dio ese resultado o deshacer sus efectos.', 'Sus efectos no se pueden deshacer.'],
    'F1.4e': [['Un borrador que una persona revisa antes de usarlo.'], ['Un dato mal registrado que se corrige en el sistema.'], ['Un puntaje de un modelo complejo que nadie puede explicar.'], ['Un pago enviado o una información ya divulgada.']],
    'F1.5': ['El resultado solo lo ve quien usa el sistema.', 'Lo ven otras personas de la entidad.', 'Se comunica a personas u organizaciones externas identificadas.', 'Se publica o se dirige al público en general.'],
    'F1.5e': [['Notas personales.'], ['Reportes internos.'], ['Respuestas a un proveedor.'], ['Un asistente abierto en la web institucional.']],
    'F2.1': ['No usa datos de personas, o están anonimizados de forma que no se puede identificar a nadie.', 'Usa datos básicos: nombre, documento, correo o teléfono.', 'Usa datos económicos, laborales o protegidos por secreto bancario o tributario.', 'Usa datos sensibles: salud, biometría, origen étnico, creencias u orientación sexual.'],
    'F2.1e': [['Estadísticas agregadas por región.'], ['Lista de contactos de proveedores.'], ['Ingresos declarados o planillas.'], ['Historias clínicas o huellas digitales.']],
    'F2.2': ['No hay personas cuyos datos se usen.', 'Pocas personas.', 'Un grupo considerable.', 'Muchas personas: gran parte de la población atendida.'],
    'F2.2e': [['Solo documentos normativos.'], ['Un equipo de trabajo.'], ['Los usuarios de una sede.'], ['Todos los beneficiarios de un programa nacional.']],
    'F2.3': ['No usa datos personales o solo usa datos públicos.', 'Usa los datos para lo mismo que se recogieron y hay base legal clara.', 'Usa los datos para algo relacionado, pero distinto; hay que analizar si es compatible.', 'Usa los datos para algo nuevo sin base legal ni consentimiento verificados.'],
    'F2.3e': [['Normas publicadas.'], ['Datos de un trámite usados para atender ese trámite.'], ['Datos de atención usados para mejorar el servicio.'], ['Datos de un trámite usados para ofrecer otros productos.']],
    'F2.4': ['No usa datos personales.', 'Los consulta en el momento y no los guarda.', 'Los guarda o los usa para entrenar o ajustar un modelo dentro de la entidad.', 'Construye perfiles de personas o un tercero usa los datos para entrenar sus modelos.'],
    'F2.4e': [['Resumir normas.'], ['Buscar el estado de un expediente para responder.'], ['Entrenar un modelo propio con datos históricos.'], ['Un proveedor que usa las conversaciones para mejorar su producto.']],
    'F2.5': ['Los datos se quedan en el Perú, o no hay datos personales.', 'Salen del país con garantías contractuales verificadas.', 'Salen del país y las garantías se están revisando.', 'Salen del país sin garantías: no debe usarse así.'],
    'F2.5e': [['Servidores de la entidad.'], ['Nube extranjera con contrato que cumple la ley peruana.'], ['Servicio extranjero cuyo contrato está en revisión legal.'], ['Una web gratuita extranjera sin contrato.']],
    'F3.3': ['No se conecta a ningún sistema: solo trabaja con lo que el usuario le escribe.', 'Puede leer información de sistemas o repositorios de la entidad.', 'Puede crear o modificar información en sistemas internos.', 'Puede actuar hacia afuera o de forma irreversible o vinculante: enviar comunicaciones, pagar, firmar, publicar.'],
    'F3.3e': [['Un chat donde se pega un texto.'], ['Un buscador sobre los documentos de la entidad.'], ['Un agente que actualiza fichas de atención.'], ['Un agente que envía respuestas oficiales o registra pagos.']],
    'F3.4': ['Solo lo usan personas de la entidad con información controlada.', 'Recibe documentos o datos enviados por terceros.', 'Lee correo, páginas web u otras fuentes externas mientras trabaja.', 'Cualquier persona desde internet puede escribirle.'],
    'F3.4e': [['Un asistente interno sobre manuales.'], ['Revisar documentos que presentan los usuarios.'], ['Un agente que lee la bandeja de correo.'], ['Un chat público en el portal institucional.']],
    'F3.5': ['Lo desarrolló la entidad con control, o el proveedor tiene certificaciones de seguridad y de gestión de IA y buenas cláusulas.', 'Proveedor evaluado, pero sin certificación específica de IA.', 'Usa componentes libres o de terceros no verificados del todo.', 'No se sabe bien quién lo desarrolló ni de dónde vienen sus componentes.'],
    'F3.5e': [['Proveedor con ISO/IEC 27001 y 42001 y contrato revisado.'], ['Proveedor conocido evaluado por el área de seguridad.'], ['Un modelo descargado de un repositorio público.'], ['Una extensión gratuita de origen desconocido.']],
    'F3.6': ['Si falla, no afecta ningún proceso importante.', 'Apoya un proceso que puede seguir manualmente sin problema.', 'Forma parte de un proceso misional importante.', 'Forma parte de un proceso crítico o de un servicio esencial.'],
    'F3.6e': [['Un asistente de redacción.'], ['Clasificación de correos con respaldo manual.'], ['Atención de trámites.'], ['Pagos, prestaciones o reportes a reguladores.']],
    AG: ['Solo responde o recomienda; no hace nada por sí mismo.', 'Prepara acciones, pero una persona las ejecuta.', 'Ejecuta acciones, pero cada una requiere aprobación previa de una persona.', 'Ejecuta acciones sin que una persona las apruebe antes.'],
    AGe: [['Un chat de preguntas y respuestas.'], ['Redacta el correo y la persona lo envía.'], ['Propone el registro y lo guarda solo si alguien aprueba.'], ['Responde y registra casos automáticamente.']]
  };
  const FT = {
    'F1.1': 'Cuánto pesa el resultado del sistema en decisiones que afectan a otros.', 'F1.2': 'A cuántas personas u organizaciones podrían afectar sus resultados.', 'F1.3': 'Si podría tratar de forma injusta a algunas personas o grupos.', 'F1.4': 'Qué tan fácil es explicar y deshacer lo que hace.', 'F1.5': 'Quién ve o recibe sus resultados.',
    'F2.1': 'Qué tan delicados son los datos personales que usa.', 'F2.2': 'De cuántas personas son los datos.', 'F2.3': 'Si los datos se usan para lo que fueron recogidos.', 'F2.4': 'Qué hace el sistema con los datos personales.', 'F2.5': 'Dónde se procesan los datos.',
    'F3.3': 'Qué puede hacer el sistema en otros sistemas: leer, escribir o actuar.', 'F3.4': 'Qué tan expuesto está a contenidos o personas externas que podrían manipularlo.', 'F3.5': 'Qué tan confiable es quién lo provee y de dónde vienen sus componentes.', 'F3.6': 'Qué tan importante es el proceso en el que se usa.', AG: 'Cuánto actúa el sistema por su cuenta.'
  };
  for (const [k, niveles] of Object.entries(F)) {
    if (k.endsWith('e')) continue;
    niveles.forEach((t, i) => { A[`${k}:${i + 1}`] = { t, e: (F[k + 'e'] || [])[i] || [] }; });
    if (FT[k]) A[k] = { t: FT[k] + ' Ante la duda entre dos niveles, elija el más alto.', e: [] };
  }

  if (typeof module !== 'undefined' && module.exports) module.exports = A;
  else root.AYUDAS = A;
})(typeof window !== 'undefined' ? window : globalThis);
