name = "contador-clasificador-ia"
main = "worker.js"
compatibility_date = "2026-09-01"

[[kv_namespaces]]
binding = "CONTADOR"
id = "0ed47fc556254a01ab490214891deae3"

[vars]
ORIGEN_PERMITIDO = "https://rriscomba.github.io"
